### ISSUE TITLE
Update core applications

### ISSUE THREAD

**Issue by riddl0rd** [mm2270/CasperSuiteScripts#2]
Hey nice script is it also possible to implement skype and google chrome?

**Comment by mm2270** [comment]
Hi Henk,

I had tried incorporating Google Chrome into the script at one point, but eventually abandoned it. Here's why:
1- Google unfortunately does not maintain a consistent easily parseable page or site anywhere that I've been able to find that stores the Mac Google Chrome's current release version to check against. The closest I've seen is their Chrome Stable Release blog. The problem though is that b/c its a blog, the text in each entry is all over the place and is impossible to extract just the version of Chrome from it, assuming its even mentioned. Sometimes they explicitly call out the version in a blog entry and sometimes they just don't. I'm still searching for one consistent place I can run curl commands against that will grab Chrome's current version number. If someone reading this knows what site or xml file or something I can run checks against, I would gladly add Chrome to the list of apps the script can update.

2- After doing some more research on Google's Software Update mechanism, it seems Chrome pretty much keeps itself up to date more accurately than I could ever do with a Casper Suite script/policy. Unless you specifically change the keystone check interval or just disable Google's automated checks on the client, a daemon runs about every 5 hours, checks all Google app versions (not just Chrome) and updates anything that needs updating.

All that said, I have a separate script that kind of adds this functionality that I can post here at some point. What it does is, if Chrome is already installed, it runs the Chrome check function already included on the client. It captures the version before and compares it after its done to see if the app was updated and displays that to the user. (i.e, Chrome was updated to version xxxx, or No new versions of Chrome right now)
If Chrome isn't installed on the Mac (in /Applications/) it offers to download and install the current release. Getting the latest version from Google is very easy as they have a consistent dmg link for whatever the latest version is. As I said, I can post that script here as well at some point so you can use it for now.
If I ever find a good way to add Chrome into my Update Core Apps script I will certainly do it.

As for Skype, this is possible, and I have looked at it. At some point in time, Skype split its versions. There is one that only works on 10.9 and up, and another version they maintain for older versions of OS X. This complicates things a little, but since I can easily grab the OS version in the script, I can probably figure out some way to make it work on any OS its running on.

**Comment by riddl0rd** [comment]
Hey Mike,

Thanks for your quick response!!! Love it.

You always take your time it seems to do good explaining i admire that.

Now about chrome i didn't know that google handle its download mechanism this wayis there a way to test

**Comment by riddl0rd** [comment]
Sorry for that replying from a phone is not that handy,

Didn't know google handle its download mechanism that way. Can i test that other script you got? Is it a cocdialog one?

We only run 10.9 an 10.10 in our shop.

Can we exchange contact details like twitter? email?

**Comment by mm2270** [comment]
Hi Henk. No worries. Email is mm2270 [at] me [dot] com. Feel free to email me there, or post here. I'll see your comments either way.

As for testing the Google script, I'll work on posting it here soon. Give me until about tomorrow or Thursday at the latest.
Right now I'm testing a correction to the Update_Core_Apps script to account for the Oracle Java version check problem you and Jason Bush ran into. Sometimes Oracle's page is a moving target. I may occasionally need to update the script whenever they decide to change around their site. But I think the version I'm about to post will fix the issue for now.
And yes, it also uses cocoaDialog for the messaging, progress bars, etc.

**Comment by mm2270** [comment]
The Update_Core_Apps script was updated to (hopefully) correct the Java version check error some were seeing with the original. Any feedback or additional issues, please post about them so I can take a look.
